# Generated by Django 3.1.6 on 2026-02-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_driverapplication_event_rideoffer_riderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='airport_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('professional', 'Professional'), ('custom', 'Custom / Personal'), ('airport', 'Airport / Flight')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='flight_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
