# Generated by Django 3.1.6 on 2026-02-24 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_seed_example_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(max_length=120)),
                ('rider_contact', models.CharField(blank=True, default='', max_length=120)),
                ('passengers_count', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='rides.person')),
            ],
        ),
    ]
