# Generated by Django 5.2.11 on 2026-03-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0005_personriderequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="person",
            name="origination_state",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="person",
            name="ride_tier",
            field=models.CharField(
                choices=[("regular", "Regular YoUber"), ("premium", "Premium YoUber")],
                default="regular",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("sedan", "Sedan"),
                    ("suv", "SUV"),
                    ("truck", "Truck"),
                    ("van", "Van"),
                    ("other", "Other"),
                ],
                default="sedan",
                max_length=10,
            ),
        ),
    ]
